---
version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    networks:
      devops_net:
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=postgres

  python-app:
    depends_on:
      - postgres
    build:
      context: ./Python
    hostname: python-app
    networks:
      devops_net:
    ports:
      - "5000:5000"


  nodejs-app:
    depends_on:
      - python-app
    build:
      context: ./NodeJs
    hostname: nodejs-app
    networks:
      devops_net:
    ports:
      - "3000:3000"

networks:
  devops_net:
